name: Fetch Fiat Rates - uses cURL

on:
  workflow_dispatch:
  #schedule:
 #   - cron: "0 8 * * *"  # Runs every day at 00:00, 08:00, and 16:00 UTC

env:
  APP_ID: ${{ secrets.APP_ID }}

permissions:
  contents: write  # Required to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: joshwhittick-patch-1-1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch fiat
        run: curl -X GET "https://openexchangerates.org/api/latest.json?app_id=${{ secrets.APP_ID }}" --output fiat-rates.json

      - name: Fetch crypto       
        run: curl -X GET "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd" --output crypto-rates.json

      - name: Commit and push changes
        run: |-
          git config --global user.email "bot@ark-builders.dev"
          git config --global user.name "ARK Builders Bot"

          git add fiat-rates.json
          git add crypto-rates.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update of fiat and crypto rates"
            git pull --rebase origin joshwhittick-patch-1-1
            git push origin joshwhittick-patch-1-1
          fi
